name: clang-format

on: [push]

jobs:
  clang-format:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: bash scripts/setup_ubuntu2204.sh --llvm 18
    - name: clang-format
      run: bash scripts/build.sh --clang-suffix -18 --clang-format
