name: clang-tidy

on: [push]

jobs:
  clang-tidy-cert:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: bash scripts/setup_ubuntu2204.sh --default
    - name: clang-tidy-cert
      run: CXX=clang++ bash scripts/build.sh --config --build --clang-tidy-cert

  clang-tidy-hicpp:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: bash scripts/setup_ubuntu2204.sh --default
    - name: clang-tidy-hicpp
      run: CXX=clang++ bash scripts/build.sh --config --build --clang-tidy-hicpp

  clang-tidy-misc:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: bash scripts/setup_ubuntu2204.sh --default
    - name: clang-tidy-misc
      run: CXX=clang++ bash scripts/build.sh --config --build --clang-tidy-misc

  clang-tidy-bugprone:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: bash scripts/setup_ubuntu2204.sh --default
    - name: clang-tidy-bugprone
      run: CXX=clang++ bash scripts/build.sh --config --build --clang-tidy-bugprone

  clang-tidy-modernize:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: bash scripts/setup_ubuntu2204.sh --default
    - name: clang-tidy-modernize
      run: CXX=clang++ bash scripts/build.sh --config --build --clang-tidy-modernize

  clang-tidy-performance:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: bash scripts/setup_ubuntu2204.sh --default
    - name: clang-tidy-performance
      run: CXX=clang++ bash scripts/build.sh --config --build --clang-tidy-performance

  clang-tidy-portability:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: bash scripts/setup_ubuntu2204.sh --default
    - name: clang-tidy-portability
      run: CXX=clang++ bash scripts/build.sh --config --build --clang-tidy-portability

  clang-tidy-readability:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: bash scripts/setup_ubuntu2204.sh --default
    - name: clang-tidy-readability
      run: CXX=clang++ bash scripts/build.sh --config --build --clang-tidy-readability

  clang-tidy-clang-analyzer:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: bash scripts/setup_ubuntu2204.sh --default
    - name: clang-tidy-clang-analyzer
      run: CXX=clang++ bash scripts/build.sh --config --build --clang-tidy-clang-analyzer

  clang-tidy-cppcoreguidelines:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: bash scripts/setup_ubuntu2204.sh --default
    - name: clang-tidy-cppcoreguidelines
      run: CXX=clang++ bash scripts/build.sh --config --build --clang-tidy-cppcoreguidelines
