name: clang-tidy

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  clang-tidy:
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        check_type: [
          misc, cert, hicpp, bugprone, modernize, performance, portability, readability,
          clang-analyzer, cppcoreguidelines]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: bash scripts/setup_ubuntu.sh --default
    - name: clang-tidy-${{matrix.check_type}}
      run: bash scripts/build.sh --clang --config --build --clang-tidy-${{matrix.check_type}}
