name: clang-format

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  clang-format:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: bash scripts/setup_ubuntu2404.sh --default
    - name: clang-format
      run: bash scripts/build.sh --clang-format
