name: coverage

on: [push]

jobs:
  llvm-cov-and-sonar:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: setup
      run: bash scripts/setup_ubuntu2204.sh --default
    - name: code quality (clang, libcpp, llvm-cov, sonar scanner)
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        CXX=clang++ bash scripts/build.sh --suffix llvm-lcov -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          --llvm-coverage --libcpp -DNANO_ENABLE_LLVM_COV=ON --config --build --test --llvm-cov --sonar
