name: cppcheck

on: [push]

jobs:
  cppcheck:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: bash scripts/setup_ubuntu2204.sh --default
    - name: cppcheck
      run: CXX=g++ bash scripts/build.sh --config --cppcheck
