name: windows-builds

on: [push]

jobs:
  build:
    name: build

    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022]
        build_type: [Release, Debug]
        build_shared_libs: [OFF, ON]

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3
    - name: build-test-install-example
      run: |
         scripts\build.bat --build-type ${{matrix.build_type}} \"-DBUILD_SHARED_LIBS=${{matrix.build_shared_libs}}\" --config --build --test --install --build-example
