name: memcheck

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  memcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: bash scripts/setup_ubuntu.sh --default
    - name: memcheck
      run: bash scripts/build.sh --gcc -DCMAKE_BUILD_TYPE=RelWithDebInfo --config --build --memcheck
