name: sanitizers

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  asan-gcc:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: bash scripts/setup_ubuntu2404.sh --default
    - name: ASAN (gcc)
      run: CXX=g++ bash scripts/build.sh -DCMAKE_BUILD_TYPE=Debug --asan --config --build --test

  lsan-gcc:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: bash scripts/setup_ubuntu2404.sh --default
    - name: LSAN (gcc)
      run: CXX=g++ bash scripts/build.sh -DCMAKE_BUILD_TYPE=Debug --lsan --config --build --test

  usan-gcc:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: bash scripts/setup_ubuntu2404.sh --default
    - name: USAN (gcc)
      run: CXX=g++ bash scripts/build.sh -DCMAKE_BUILD_TYPE=Debug --usan --config --build --test

  tsan-gcc:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: bash scripts/setup_ubuntu2404.sh --default
    - name: TSAN (gcc)
      run: CXX=g++ bash scripts/build.sh -DCMAKE_BUILD_TYPE=Debug --tsan --config --build --test
