name: sanitizers

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  asan-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: bash scripts/setup_ubuntu.sh --default
    - name: ASAN (clang)
      run: bash scripts/build.sh --clang -DCMAKE_BUILD_TYPE=Debug --asan --config --build --test

  lsan-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: bash scripts/setup_ubuntu.sh --default
    - name: LSAN (clang)
      run: bash scripts/build.sh --clang -DCMAKE_BUILD_TYPE=Debug --lsan --config --build --test

  usan-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: bash scripts/setup_ubuntu.sh --default
    - name: USAN (clang)
      run: bash scripts/build.sh --clang -DCMAKE_BUILD_TYPE=Debug --usan --config --build --test

  tsan-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: bash scripts/setup_ubuntu.sh --default
    - name: TSAN (clang)
      run: bash scripts/build.sh --clang -DCMAKE_BUILD_TYPE=Debug --tsan --config --build --test
